### ISSUE TITLE
set_camera_info Service not found

### ISSUE THREAD

**Issue by jmtatsch** [fpasteau/raspicam_node#2]
Hello,

how can I calibrate my raspicam?

```
phoenix@phoenix ~/ros_catkin_ws/src/raspicam_node $ rostopic list
/camera/camera_info
/camera/image/compressed
/rosout
/rosout_agg
phoenix@phoenix ~/ros_catkin_ws/src/raspicam_node $ rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image/compressed camera:=/camera
('Waiting for service', '/camera/set_camera_info', '...')
Service not found
phoenix@phoenix ~/ros_catkin_ws/src/raspicam_node $ rosservice list
/Camera/get_loggers
/Camera/set_logger_level
/camera/start_capture
/camera/stop_capture
/rosout/get_loggers
/rosout/set_logger_level
/set_camera_info

```

the service cannot be found although it is there? did you manage to calibrate it with the camera_calibration package? can you give me a hint?

**Comment by fpasteau** [comment]
Hi,
First, because the name of the service is /set_camera_info, the command line to call camera_calibration should look like this : 
<code>
rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image/compressed camera:=/
</code>

Secondly, the cameracalibration node expects the image topic to be in a raw format. Therefore you need to republish the compressed topic into a raw one. This can be done using the following command line : 
<code>
rosrun image_transport republish compressed in:=/camera/image raw out:=/camera/image
</code>

Finally, to sum up, to calibrate the camera you should : 
- 1 . Start the raspicam node with 
<code>
rosrun raspicam raspicam_node
</code>
- 2 . Start the capture with
<code>
rosservice call /camera/start_capture
</code>
- 3 . Republish the compressed topic using
<code>
rosrun image_transport republish compressed in:=/camera/image raw out:=/camera/image
</code>
- 4 . Start the calibration using
<code>
rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image/compressed camera:=/
</code>

For speed purposes, it is usually faster to do step 3 and 4 on a computer and not directly on the Raspberry Pi.

I hope this will help you.

**Comment by jmtatsch** [comment]
Thank you very much. I'm positive this will do the trick.

**Comment by jmtatsch** [comment]
Are you sure about the last part:
'rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image/compressed camera:=/'
shouldn't that be?
'rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image camera:=/camera'
However for both the calibrator segfaults instantly:                                       
[1]    40787 segmentation fault  rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108
with no other hints.

/camera/image seems to be remapped correctly, at least the stream is viewable.

When everything is run directly on the raspberrypi i get a datatype mismatch:

``` [ INFO] [1430408483.738287512]: camera calibration URL: package://raspicam/calibrations/camera.yaml
[ERROR] [1430408483.945197446]: Unable to create YAML parser for camera calibration
[ERROR] [1430408483.945680253]: Failed to parse camera calibration from file [/home/phoenix/ros_catkin_ws/src/raspicam_node/calibrations/camera.yaml]
[ WARN] [1430408483.946236446]: Camera calibration file /home/phoenix/ros_catkin_ws/src/raspicam_node/calibrations/camera.yaml not found.
[ INFO] [1430408483.946896960]: Calibration file missing. Camera not calibrated
[ INFO] [1430408484.805726119]: Camera component done

[ INFO] [1430408484.813098961]: Encoder component done

[ INFO] [1430408484.829709001]: Starting video capture (640, 480, 80, 30)

[ INFO] [1430408484.831752730]: Video capture started

[CaptureStarter-3] process has finished cleanly
log file: /home/phoenix/.ros/log/5817a606-ef4f-11e4-bbc7-24050f345323/CaptureStarter-3*.log
[ERROR] [1430408486.023625284]: Client [/Calibrator] wants topic /camera/image/compressed to have datatype/md5sum [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743], but our version has [sensor_msgs/CompressedImage/8f7a12909da2c9d3332d540a0977563f]. Dropping connection.

(display:3995): Gtk-WARNING **: cannot open display: 
[Calibrator-5] process has died [pid 3995, exit code 1, cmd /home/phoenix/ros_catkin_ws/src/camera_calibration/nodes/cameracalibrator.py --size 9x6 --square 0.03 image:=/camera/image/compressed camera:=/ __name:=Calibrator __log:=/home/phoenix/.ros/log/5817a606-ef4f-11e4-bbc7-24050f345323/Calibrator-5.log].
log file: /home/phoenix/.ros/log/5817a606-ef4f-11e4-bbc7-24050f345323/Calibrator-5*.log
```
Any more hints for me?

**Comment by jmtatsch** [comment]
Bump?

**Comment by fpasteau** [comment]
A part of it is right and for the other I made a typo. The correct command line should be 
<code>
rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image camera:=/
</code>
The calibrator expects the image topic to be in a raw format.That's why it is first republished in a raw format using <code>rosrun image_transport republish compressed in:=/camera/image raw out:=/camera/image</code>. We then use the <code>/camera/image</code> raw topic using <code>image:=/camera/image</code>.
As for <code>camera:=/</camera></code>, it is necessary as the service used to save the calibration setting is located at <code>/set_camera_info</code> instead of <code> /camera/set_camera_info </code>.

I've corrected my comment above in case someone read it for calibration.

As for your second issue, you have a mismatch between the type the calibrator expects (raw) and the type the raspicam node provides (compressed). I guess It's either due to the fact that you didn't republish the compressed image topic into a raw one using the republish node or that you didn't set the right image input topic for the calibrator.

I hope this will help.
If it still does not work, send me all the command lines that you typed and I'll try to see if I find something wrong.

**Comment by jmtatsch** [comment]
It worked! Thank you very much!

**Comment by theamazingdrew** [comment]
I just ran across this. For anyone in the future, also worth noting is that, instead of republishing your image as a raw file, you may just want to check your code to see if it's subscribing to a raw or compressed file.

For example (I was recently writing a python subscriber), instead of:

`from sensor_msgs.msg import Image`
use
`from sensor_msgs.msg import CompressedImage`

And then use that in your code. That way you don't have to have any dependencies outside of your node for it to work.

And when you go to get the image on the subscriber's end, don't forget to use the right code to decompress if over there as well, such as: 

`cv2_img = bridge.compressed_imgmsg_to_cv2(msg, "bgr8")`

**Comment by theamazingdrew** [comment]
I just ran across this. For anyone in the future, also worth noting is that, instead of republishing your image as a raw file, you may just want to check your code to see if it's subscribing to a raw or compressed file.

For example (I was recently writing a python subscriber), instead of:

`from sensor_msgs.msg import Image`
use
`from sensor_msgs.msg import CompressedImage`

And then use that in your code. That way you don't have to have any dependencies outside of your node for it to work.
